

export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",

  FORBIDDEN: "FORBIDDEN",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  EMAIL_ALREADY_EXIST: "EMAIL_ALREADY_EXIST",

  INVALID_OBJECT_ID: "INVALID_OBJECT_ID",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;