
export const PERMISSIONS = {

    TEAM_CREATE: "TEAM_CREATE",
    TEAM_UPDATE: "TEAM_UPDATE",
    TEAM_VIEW: "TEAM_VIEW",
    TEAM_DELETE: "TEAM_DELETE",

    EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
    EMPLOYEE_UPDATE:"EMPLOYEE_UPDATE",
    EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
    EMPLOYEE_DELETE: "EMPLOYEE_DELETE",

    PROJECT_CREATE: "PROJECT_CREATE",
    PROJECT_UPDATE: "PROJECT_UPDATE",
    PROJECT_VIEW: "PROJECT_VIEW",
    PROJECT_DELETE: "PROJECT_DELETE"

} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];